# Generated by Django 3.1.7 on 2021-04-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageName',
            field=models.CharField(default='missing.jpg', max_length=32),
        ),
    ]
