# Generated by Django 3.1.7 on 2021-05-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210502_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercartorder',
            name='orderDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customercartorder',
            name='shippedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
