# Generated by Django 3.1.7 on 2021-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210502_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='vendor',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
