# Generated by Django 3.1.7 on 2021-05-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_importorder_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderindividual',
            name='vendorUnitPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
