# Generated by Django 3.1.7 on 2021-05-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cartorderindividual_vendorunitprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderindividual',
            old_name='vendorUnitPrice',
            new_name='vendorPrice',
        ),
    ]
