# Generated by Django 3.1.7 on 2021-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210503_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderindividual',
            name='vendorPrice',
        ),
        migrations.AddField(
            model_name='importorder',
            name='vendorPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
