# Generated by Django 3.2 on 2021-05-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210503_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageName',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Image'),
        ),
    ]
